import json
from pathlib import Path

notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 07. Empirical Crypto Strategy Backtest — Finding Quantitative Edge\n",
    "\n",
    "This notebook evaluates **5 Institutional Quantitative Crypto Trading Strategies** across 8 high-liquidity Binance pairs (`BTCUSDT`, `ETHUSDT`, `SOLUSDT`, `BNBUSDT`, `XRPUSDT`, `AVAXUSDT`, `NEARUSDT`, `DOGEUSDT`) on **1-hour candles**.\n",
    "\n",
    "### Friction & Execution Parameters:\n",
    "- **Binance Taker Fee**: 0.075%\n",
    "- **Slippage**: 0.05% per trade side\n",
    "- **Round Trip Friction**: **0.25%**\n",
    "- **Risk Management**: Dynamic ATR Stop-Loss ($1.5 \\times \\text{ATR}$) & Take-Profit ($2.0 \\times \\text{ATR}$)\n",
    "\n",
    "### Tested Strategies:\n",
    "1. **Macro Regime RSI Pullback (200 EMA + RSI Dip)** — Buying pullbacks in confirmed bull regimes\n",
    "2. **StochRSI Oversold Trend Filter (50/200 EMA)** — Momentum recovery in macro trend\n",
    "3. **TTM Squeeze Breakout + Volume Surge** — Volatility contraction expansion with RVOL > 1.5\n",
    "4. **Supertrend Flip + Macro 200 EMA Filter** — Trend continuation following Supertrend flip\n",
    "5. **Volume Surge Breakout (RVOL > 1.8 + MACD)** — Volume confirmation momentum"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "from pathlib import Path\n",
    "project_root = Path.cwd() if (Path.cwd() / \"backend\").exists() else Path.cwd().parent\n",
    "if str(project_root) not in sys.path:\n",
    "    sys.path.append(str(project_root))\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly.graph_objects as go\n",
    "import plotly.express as px\n",
    "from backend.binance_client import binance_client\n",
    "from backend.indicators import enrich_klines_dataframe\n",
    "\n",
    "SYMBOLS = ['BTCUSDT', 'ETHUSDT', 'SOLUSDT', 'BNBUSDT', 'XRPUSDT', 'AVAXUSDT', 'NEARUSDT', 'DOGEUSDT']\n",
    "INTERVAL = '1h'\n",
    "LIMIT = 1000\n",
    "TOTAL_FRICTION = 0.0025  # 0.25% round trip fee + slippage\n",
    "\n",
    "print('Loading market data for backtesting...')\n",
    "datasets = {}\n",
    "for sym in SYMBOLS:\n",
    "    try:\n",
    "        raw = binance_client.get_klines(sym, interval=INTERVAL, limit=LIMIT)\n",
    "        df = enrich_klines_dataframe(raw)\n",
    "        if not df.empty and len(df) >= 100:\n",
    "            datasets[sym] = df\n",
    "            print(f'Loaded {sym}: {len(df)} candles')\n",
    "    except Exception as e:\n",
    "        print(f'Failed to load {sym}: {e}')\n",
    "\n",
    "print(f'Ready! Total pairs: {len(datasets)}')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Define Strategy Logic Functions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "def strat_macro_trend_pullback(df):\n",
    "    \"\"\"Macro 200 EMA + RSI Pullback (< 40)\"\"\"\n",
    "    macro_uptrend = df['close'] > df['ema_200']\n",
    "    rsi_pullback = (df['rsi'].shift(1) < 40) & (df['rsi'] >= 40)\n",
    "    ema_bullish = df['ema_8'] > df['ema_21']\n",
    "    return macro_uptrend & rsi_pullback & ema_bullish\n",
    "\n",
    "def strat_stoch_rsi_trend_filter(df):\n",
    "    \"\"\"StochRSI Oversold in 50/200 EMA Uptrend\"\"\"\n",
    "    uptrend = (df['close'] > df['ema_200']) & (df['ema_50'] > df['ema_200'])\n",
    "    stoch_cross = (df['stoch_k'].shift(1) <= df['stoch_d'].shift(1)) & (df['stoch_k'] > df['stoch_d']) & (df['stoch_k'].shift(1) < 20)\n",
    "    return uptrend & stoch_cross\n",
    "\n",
    "def strat_bb_squeeze_volume(df):\n",
    "    \"\"\"TTM Squeeze + RVOL > 1.5\"\"\"\n",
    "    squeeze_on = (df['bb_upper'].shift(1) < df['kc_upper'].shift(1)) & (df['bb_lower'].shift(1) > df['kc_lower'].shift(1))\n",
    "    breakout = (df['close'] > df['bb_upper']) & (df['rvol'] > 1.5)\n",
    "    return squeeze_on & breakout\n",
    "\n",
    "def strat_supertrend_regime(df):\n",
    "    \"\"\"Supertrend Flip + Macro 200 EMA Filter\"\"\"\n",
    "    macro_uptrend = df['close'] > df['ema_200']\n",
    "    st_flip = (df['supertrend_dir'].shift(1) == -1) & (df['supertrend_dir'] == 1)\n",
    "    return macro_uptrend & st_flip\n",
    "\n",
    "def strat_volume_breakout_regime(df):\n",
    "    \"\"\"RVOL > 1.8 + MACD + 200 EMA Filter\"\"\"\n",
    "    macro_uptrend = df['close'] > df['ema_200']\n",
    "    vol_surge = df['rvol'] > 1.8\n",
    "    macd_hist_cross = (df['macd_hist'].shift(1) <= 0) & (df['macd_hist'] > 0)\n",
    "    return macro_uptrend & vol_surge & macd_hist_cross\n",
    "\n",
    "STRATEGIES = {\n",
    "    'Macro Regime RSI Pullback': strat_macro_trend_pullback,\n",
    "    'StochRSI Oversold Trend Filter': strat_stoch_rsi_trend_filter,\n",
    "    'TTM Squeeze Breakout': strat_bb_squeeze_volume,\n",
    "    'Supertrend + 200 EMA Filter': strat_supertrend_regime,\n",
    "    'Volume Breakout (RVOL > 1.8)': strat_volume_breakout_regime\n",
    "}\n",
    "\n",
    "print('Strategies registered successfully.')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Backtesting Execution Engine with Dynamic ATR Risk Management"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "def backtest_engine(df, signal_mask, sl_mult=1.5, tp_mult=2.0):\n",
    "    trades = []\n",
    "    n = len(df)\n",
    "    indices = np.where(signal_mask)[0]\n",
    "    \n",
    "    for idx in indices:\n",
    "        if idx >= n - 1: continue\n",
    "        entry_p = df['close'].iloc[idx]\n",
    "        atr = df['atr'].iloc[idx]\n",
    "        if np.isnan(atr) or atr <= 0: atr = entry_p * 0.01\n",
    "        \n",
    "        entry_eff = entry_p * (1 + TOTAL_FRICTION)\n",
    "        sl_p = entry_p - (sl_mult * atr)\n",
    "        tp_p = entry_p + (tp_mult * atr)\n",
    "        \n",
    "        exit_p = None\n",
    "        reason = 'TIMED_OUT'\n",
    "        max_bars = min(n, idx + 49)\n",
    "        \n",
    "        for f_idx in range(idx + 1, max_bars):\n",
    "            h, l = df['high'].iloc[f_idx], df['low'].iloc[f_idx]\n",
    "            if l <= sl_p:\n",
    "                exit_p = sl_p * (1 - TOTAL_FRICTION)\n",
    "                reason = 'STOP_LOSS'\n",
    "                break\n",
    "            elif h >= tp_p:\n",
    "                exit_p = tp_p * (1 - TOTAL_FRICTION)\n",
    "                reason = 'TAKE_PROFIT'\n",
    "                break\n",
    "        if exit_p is None:\n",
    "            exit_p = df['close'].iloc[max_bars - 1] * (1 - TOTAL_FRICTION)\n",
    "            \n",
    "        ret = ((exit_p - entry_eff) / entry_eff) * 100\n",
    "        trades.append({'entry_time': df['open_time'].iloc[idx], 'return_pct': ret, 'reason': reason})\n",
    "        \n",
    "    return pd.DataFrame(trades)\n",
    "\n",
    "results = []\n",
    "equity_curves = {}\n",
    "\n",
    "for name, fn in STRATEGIES.items():\n",
    "    all_tr = []\n",
    "    for sym, df in datasets.items():\n",
    "        tr = backtest_engine(df, fn(df))\n",
    "        if not tr.empty: all_tr.append(tr)\n",
    "    if all_tr:\n",
    "        comb = pd.concat(all_tr, ignore_index=True).sort_values('entry_time')\n",
    "        ret = comb['return_pct']\n",
    "        wins = ret[ret > 0]\n",
    "        losses = ret[ret <= 0]\n",
    "        \n",
    "        cum = (1 + ret / 100).cumprod()\n",
    "        equity_curves[name] = cum\n",
    "        rmax = cum.cummax()\n",
    "        dd = ((cum - rmax) / rmax) * 100\n",
    "        \n",
    "        results.append({\n",
    "            'Strategy': name,\n",
    "            'Trades': len(ret),\n",
    "            'Win Rate (%)': round((len(wins)/len(ret))*100, 2),\n",
    "            'Avg Return (%)': round(ret.mean(), 2),\n",
    "            'Total Compounded (%)': round(((1 + ret/100).prod() - 1)*100, 2),\n",
    "            'Profit Factor': round(wins.sum() / abs(losses.sum() + 1e-10), 2),\n",
    "            'Max Drawdown (%)': round(dd.min(), 2),\n",
    "            'Sharpe Ratio': round((ret.mean()/ret.std())*np.sqrt(8760/24), 2) if ret.std() > 0 else 0,\n",
    "        })\n",
    "\n",
    "df_results = pd.DataFrame(results).sort_values('Profit Factor', ascending=False)\n",
    "df_results"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Plot Cumulative Equity Curves"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "fig = go.Figure()\n",
    "for strat_name, curve in equity_curves.items():\n",
    "    fig.add_trace(go.Scatter(y=curve.values, mode='lines', name=strat_name))\n",
    "\n",
    "fig.update_layout(\n",
    "    title='Crypto Strategy Equity Curves (1h Timeframe - 1000 Candles)',\n",
    "    xaxis_title='Trade Number',\n",
    "    yaxis_title='Growth of $1.00 Investment',\n",
    "    template='plotly_dark',\n",
    "    height=500\n",
    ")\n",
    "fig.show()"
   ]
  }
 ]
}

notebook_path = Path("notebooks/07_profitable_strategies_backtest.ipynb")
with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(notebook_content, f, indent=1)

print("Created notebooks/07_profitable_strategies_backtest.ipynb successfully!")
